import 'dart:ui';

import 'package:injectable/injectable.dart';

import '../../l10n/gen/app_localizations.dart';
import '../domain/entities/app_notification_channel.dart';
import '../domain/repositories/notification_messages.dart';

/// Resolves notification copy against the device locale.
///
/// Uses `lookupAppLocalizations` (generated by `flutter gen-l10n`, and
/// synchronous) instead of `AppLocalizations.of(context)`, because a
/// notification is composed from a use case that has no `BuildContext` — the
/// strings still come from the `.arb`, which is what the rule protects.
@LazySingleton(as: NotificationMessages)
class LocalizedNotificationMessages implements NotificationMessages {
  const LocalizedNotificationMessages();

  /// Fallback when the device locale is not one billetudo ships. Spanish is
  /// the product's primary market, so it is the floor, not English.
  static const Locale _fallbackLocale = Locale('es');

  AppLocalizations get _l10n {
    final deviceLocale = PlatformDispatcher.instance.locale;
    final isSupported = AppLocalizations.supportedLocales.any(
      (supported) => supported.languageCode == deviceLocale.languageCode,
    );
    return lookupAppLocalizations(
      isSupported ? Locale(deviceLocale.languageCode) : _fallbackLocale,
    );
  }

  @override
  String channelName(AppNotificationChannel channel) => switch (channel) {
        AppNotificationChannel.reminders =>
          _l10n.notificationsChannelRemindersName,
        AppNotificationChannel.captures =>
          _l10n.notificationsChannelCapturesName,
        AppNotificationChannel.milestones =>
          _l10n.notificationsChannelMilestonesName,
      };

  @override
  String channelDescription(AppNotificationChannel channel) =>
      switch (channel) {
        AppNotificationChannel.reminders =>
          _l10n.notificationsChannelRemindersDescription,
        AppNotificationChannel.captures =>
          _l10n.notificationsChannelCapturesDescription,
        AppNotificationChannel.milestones =>
          _l10n.notificationsChannelMilestonesDescription,
      };

  @override
  String scheduledPaymentReminderTitle(String templateName) => templateName;

  @override
  String scheduledPaymentReminderBody({
    required int leadDays,
    required String formattedAmount,
    required String accountName,
  }) {
    final l10n = _l10n;
    return switch (leadDays) {
      <= 0 => l10n.remindersNotificationBodyToday(formattedAmount, accountName),
      1 => l10n.remindersNotificationBodyTomorrow(formattedAmount, accountName),
      _ => l10n.remindersNotificationBodyInDays(
          leadDays,
          formattedAmount,
          accountName,
        ),
    };
  }

  @override
  String get scheduledPaymentUntitled => _l10n.scheduledPaymentUntitled;
}
