name: billetudo_lints_example
description: Fixtures que verifican cada regla de billetudo_lints.
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  custom_lint: ^0.8.1
  billetudo_lints:
    path: ../
