import 'package:flutter/material.dart';

import '../../../../core/theme/app_colors.dart';
import '../../../../core/theme/app_theme.dart';
import '../../../../core/utils/money_formatter.dart';
import '../../../transactions/domain/entities/transaction.dart' as tx;
import '../utils/scheduled_payment_format.dart';
import 'scheduled_category_icon_wrap.dart';

/// One row of the detail page's "Ya generados" list (criterion 13): the
/// category icon tile, the template's name over "Cuenta · fecha", and the
/// amount — the same anatomy the rest of the feature's rows use, instead of
/// a generic receipt icon plus a bare date.
///
/// The name/account/category come from the template (every row here was
/// generated by it), not from the transaction, which only carries ids.
class ScheduledPaymentHistoryRow extends StatelessWidget {
  const ScheduledPaymentHistoryRow({
    required this.transaction,
    required this.name,
    required this.accountName,
    required this.onTap,
    this.isTransfer = false,
    this.categoryIcon,
    this.categoryColor,
    super.key,
  });

  final tx.Transaction transaction;

  /// Already resolved by the caller with `ScheduledPaymentFormat.templateName`.
  final String name;

  final String accountName;
  final bool isTransfer;
  final String? categoryIcon;
  final String? categoryColor;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    final colors = context.colors;
    final theme = Theme.of(context);
    return Material(
      color: colors.surface,
      borderRadius: BorderRadius.circular(AppTheme.radiusLarge),
      child: InkWell(
        onTap: onTap,
        borderRadius: BorderRadius.circular(AppTheme.radiusLarge),
        child: Padding(
          padding: const EdgeInsets.all(12),
          child: Row(
            children: [
              ScheduledCategoryIconWrap(
                isTransfer: isTransfer,
                categoryIcon: categoryIcon,
                categoryColor: categoryColor,
                size: 36,
                iconSize: 18,
                cornerRadius: 14,
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      name,
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                      style: theme.textTheme.bodyMedium
                          ?.copyWith(fontWeight: FontWeight.w700),
                    ),
                    const SizedBox(height: 2),
                    Text(
                      '$accountName · '
                      '${ScheduledPaymentFormat.shortDateLabel(context, transaction.date)}',
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                      style: theme.textTheme.bodySmall
                          ?.copyWith(color: colors.textSecondary),
                    ),
                  ],
                ),
              ),
              const SizedBox(width: 8),
              Text(
                const MoneyFormatter().formatSymbol(
                  transaction.amountMinor,
                  currencyCode: transaction.currency,
                ),
                style: theme.textTheme.titleSmall
                    ?.copyWith(fontWeight: FontWeight.w700),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
